Add new metadata folder structure
vtex-apps/google-customer-reviews pull request #8
Opened 2020-08-19 21:03 UTC by marlonguimaraes

**What problem is this solving?**

**How should this be manually tested?**

**Screenshots or example usage:**

2020-08-31 21:01 UTC, marlonguimaraes reviewed
Missing `metricDescription`

2020-09-09 19:12 UTC, klzns requested changes

2020-09-09 19:12 UTC, klzns commented on crowdin.yml
> +    translation: "/google-customer-reviews/public/metadata/licenses/%locale%.md"
I think we can remove this. I'm basing on this commit:
https://github.com/vtex-apps/tawk-to/commit/b36277f105328aea4521e016ded600e4eda88df4

```suggestion
    source: "/public/metadata/messages/pt-BR.json"
    translation: "/public/metadata/messages/%locale%.json"
    type: "json"
  -
    source: "/public/metadata/licenses/pt-BR.md"
    translation: "/public/metadata/licenses/%locale%.md"
```

2020-09-09 22:06 UTC, manoel-gumes approved these changes

2020-09-09 22:06 UTC, manoel-gumes approved these changes

2020-09-15 00:24 UTC, klzns approved these changes

2020-09-15 15:07 UTC, merged